language: node_js
node_js:
  - 10
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - npm run build-docs
  - npm run build-erisplus- docs
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
deploy:
  provider: pages:git
  edge: true
  repo: nfearnley/Mei-docs
  deploy_key: $GITHUB_DOCS_TOKEN
  local_dir: jsdocs