language: node_js
node_js:
  - 10
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - ls
  - npm run build-docs
  - npm run build-erisplus-docs
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    repo: nfearnley/Mei-docs
    target_branch: develop
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: develop
  - provider: pages
    skip_cleanup: true
    keep_history: true
    repo: nfearnley/Mei-docs
    target_branch: master
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
